# Generated by Django 2.1.15 on 2020-08-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orgunit_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgunit',
            old_name='acronim',
            new_name='acronym',
        ),
    ]
