# Generated by Django 2.1.15 on 2020-08-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200831_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='acronym',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orgunit',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
