# Generated by Django 2.1.15 on 2020-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200831_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='acronym',
            field=models.CharField(blank=True, default=None, max_length=3),
        ),
    ]
