# Generated by Django 2.1.15 on 2020-08-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200831_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='acronym',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
