# Generated by Django 2.1.15 on 2020-08-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200831_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgunit',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
